// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpqfvbpsdhzsxtkxundn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwcWZ2YnBzZGh6c3h0a3h1bmRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTE0ODc1NDEsImV4cCI6MjEwNzA2MzU0MX0.kUx9yLDoIYlOGofN5XQJGtBDU_4ICtme6BZuyHgaFJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});